import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { api } from '../api/client'
import { BarChart3, Download, Calendar, Loader2 } from 'lucide-react'
import { toast } from 'sonner'
import { useState } from 'react'

export default function Reports() {
  const queryClient = useQueryClient()
  const { data: reports, isLoading } = useQuery({ queryKey: ['reports'], queryFn: api.getReports })
  const [downloading, setDownloading] = useState<string | null>(null)
  
  const generateMutation = useMutation({
    mutationFn: () => api.createReport({ title: `Incident Summary Report - ${new Date().toLocaleDateString()}` }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['reports'] })
      toast.success('Report Generated', { description: 'The new report is now available for download.' })
    },
    onError: (err: any) => toast.error('Failed to generate report', { description: err.message })
  })

  const handleDownload = async (reportId: string) => {
    setDownloading(reportId)
    try {
      const blob = await api.downloadReport(reportId)
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${reportId}.pdf`
      document.body.appendChild(a)
      a.click()
      window.URL.revokeObjectURL(url)
      document.body.removeChild(a)
    } catch (err: any) {
      toast.error('Download Failed', { description: err.message || 'Could not download the report.' })
    } finally {
      setDownloading(null)
    }
  }

  if (isLoading) return <div className="p-8 text-text-disabled">Loading reports...</div>

  return (
    <div className="animate-in fade-in duration-500 max-w-[1600px] mx-auto pb-12">
      <div className="flex justify-between items-center mb-8 pb-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-text-primary">Reports</h1>
          <p className="text-text-secondary mt-1">Generated analytical and compliance reports.</p>
        </div>
        <button 
          onClick={() => generateMutation.mutate()}
          disabled={generateMutation.isPending}
          className="bg-surface border border-border hover:bg-background text-text-primary px-4 py-2 rounded-lg font-bold shadow-sm transition-colors flex items-center gap-2 text-sm disabled:opacity-50"
        >
          {generateMutation.isPending ? <Loader2 size={16} className="animate-spin" /> : <Calendar size={16} />} 
          Generate New Report
        </button>
      </div>

      <div className="bg-surface border border-border rounded-xl shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead className="bg-background border-b border-border">
              <tr>
                <th className="text-xs uppercase tracking-wider font-bold text-text-secondary p-4">Report Title</th>
                <th className="text-xs uppercase tracking-wider font-bold text-text-secondary p-4">Generated By</th>
                <th className="text-xs uppercase tracking-wider font-bold text-text-secondary p-4">Date</th>
                <th className="text-xs uppercase tracking-wider font-bold text-text-secondary p-4 text-right">Action</th>
              </tr>
            </thead>
            <tbody>
              {reports?.length === 0 ? (
                <tr><td colSpan={4} className="p-8 text-center text-text-disabled">No reports generated yet.</td></tr>
              ) : (
                reports?.map((report: any) => (
                  <tr key={report.id} className="border-b border-border hover:bg-background transition-colors">
                    <td className="p-4 font-bold text-text-primary flex items-center gap-3">
                      <BarChart3 size={18} className="text-secondary" /> {report.title}
                    </td>
                    <td className="p-4 text-sm text-text-secondary">{report.generated_by}</td>
                    <td className="p-4 text-sm text-text-secondary">
                      {new Date(report.created_at).toLocaleDateString()}
                    </td>
                    <td className="p-4 text-right">
                      <button 
                        onClick={() => handleDownload(report.id)}
                        disabled={downloading === report.id}
                        className="inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline disabled:opacity-50"
                      >
                        {downloading === report.id ? <Loader2 size={14} className="animate-spin" /> : <Download size={14} />} 
                        Download PDF
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
