import { useQuery } from '@tanstack/react-query'
import { api } from '../api/client'
import { BarChart3, Download, Calendar } from 'lucide-react'

export default function Reports() {
  const { data: reports, isLoading } = useQuery({ queryKey: ['reports'], queryFn: api.getReports })

  if (isLoading) return <div className="p-8 text-text-disabled">Loading reports...</div>

  return (
    <div className="animate-in fade-in duration-500 max-w-[1600px] mx-auto pb-12">
      <div className="flex justify-between items-center mb-8 pb-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-text-primary">Reports</h1>
          <p className="text-text-secondary mt-1">Generated analytical and compliance reports.</p>
        </div>
        <button className="bg-surface border border-border hover:bg-background text-text-primary px-4 py-2 rounded-lg font-bold shadow-sm transition-colors flex items-center gap-2 text-sm">
          <Calendar size={16} /> Generate New Report
        </button>
      </div>

      <div className="bg-surface border border-border rounded-xl shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead className="bg-background border-b border-border">
              <tr>
                <th className="text-xs uppercase tracking-wider font-bold text-text-secondary p-4">Report Title</th>
                <th className="text-xs uppercase tracking-wider font-bold text-text-secondary p-4">Generated By</th>
                <th className="text-xs uppercase tracking-wider font-bold text-text-secondary p-4">Date</th>
                <th className="text-xs uppercase tracking-wider font-bold text-text-secondary p-4 text-right">Action</th>
              </tr>
            </thead>
            <tbody>
              {reports?.length === 0 ? (
                <tr><td colSpan={4} className="p-8 text-center text-text-disabled">No reports generated yet.</td></tr>
              ) : (
                reports?.map((report: any) => (
                  <tr key={report.id} className="border-b border-border hover:bg-background transition-colors">
                    <td className="p-4 font-bold text-text-primary flex items-center gap-3">
                      <BarChart3 size={18} className="text-secondary" /> {report.title}
                    </td>
                    <td className="p-4 text-sm text-text-secondary">{report.generated_by}</td>
                    <td className="p-4 text-sm text-text-secondary">
                      {new Date(report.created_at).toLocaleDateString()}
                    </td>
                    <td className="p-4 text-right">
                      <button className="inline-flex items-center gap-1 text-sm font-medium text-primary hover:underline">
                        <Download size={14} /> Download PDF
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
